version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    
    # build:
    #   context: .
    #   dockerfile: frontend/DOCKERFILE
    image: torreangular # image repository or image name 
    restart: always
    ports:
      - '127.0.0.1:80:80'
    volumes: 
      - data-vol:/data

  node: #name of the second service
    image: lupanode # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    links:
      - database # link this service to the database service
    volumes: 
      - data-vol:/data
  
  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding
    volumes: 
      - data-vol:/data

volumes: 
 data-vol: 